// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC0F46dfzY9EgThDZqNvlvnGMqmvhyhbd0',
    appId: '1:854268445605:web:170ac19257f750b23a5e4c',
    messagingSenderId: '854268445605',
    projectId: 'prototype-a9bab',
    authDomain: 'prototype-a9bab.firebaseapp.com',
    databaseURL: 'https://prototype-a9bab-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'prototype-a9bab.appspot.com',
    measurementId: 'G-6YC4SNQ9DC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDFDAfvNHDThLeNBHNTEDtvjxLXTtcCYDo',
    appId: '1:854268445605:android:6195e8cdb1929c693a5e4c',
    messagingSenderId: '854268445605',
    projectId: 'prototype-a9bab',
    databaseURL: 'https://prototype-a9bab-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'prototype-a9bab.appspot.com',
  );
}
